set shell := ["bash", "-cu"]

app_name      := "WhisprKing"
bundle_id     := "com.devmaxde.whisprking"
version       := "0.1.0"

bin           := "target/release/whisprking"
bin_debug     := "target/debug/whisprking"

bundle_dir    := "target/release/bundle"
app_bundle    := bundle_dir + "/" + app_name + ".app"
install_root  := "/Applications"
installed_app := install_root + "/" + app_name + ".app"

dmg_staging   := bundle_dir + "/dmg"
dmg_rw        := bundle_dir + "/" + app_name + "-rw.dmg"
dmg           := bundle_dir + "/" + app_name + "-" + version + ".dmg"

# Default: show available recipes
default:
    @just --list

# --- build -----------------------------------------------------------------

# Build release binary + ad-hoc codesign so Accessibility trust survives rebuilds
build:
    cargo build --release
    codesign --force --sign - {{bin}}
    @echo "signed: {{bin}}"
    @codesign -dv {{bin}} 2>&1 | sed 's/^/  /'

# Debug build + sign (slower runtime, faster compile)
build-debug:
    cargo build
    codesign --force --sign - {{bin_debug}}

# Release build with sherpa-onnx backend (NVIDIA NeMo Parakeet). First build ~10 min.
build-sherpa:
    cargo build --release --features sherpa
    codesign --force --sign - {{bin}}
    @echo "signed: {{bin}}"

# --- bundle ----------------------------------------------------------------

# Wrap whatever release binary already exists into a .app. Build-agnostic:
# works for both plain and sherpa builds. Fails if the binary is missing.
_bundle:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -f "{{bin}}" ]; then
        echo "missing {{bin}} — run 'just build' (or 'just build-sherpa') first" >&2
        exit 1
    fi
    rm -rf "{{app_bundle}}"
    mkdir -p "{{app_bundle}}/Contents/MacOS"
    mkdir -p "{{app_bundle}}/Contents/Resources"
    cp "{{bin}}" "{{app_bundle}}/Contents/MacOS/{{app_name}}"
    # The icon is generated by the binary itself (src/ui/brand.rs), so the
    # bundle icon, the menu-bar icon and the mark in the app can never drift
    # apart, and no image assets live in the repo.
    "{{bin}}" --write-icns "{{app_bundle}}/Contents/Resources/AppIcon.icns"
    cat > "{{app_bundle}}/Contents/Info.plist" <<PLIST
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>CFBundleName</key><string>{{app_name}}</string>
        <key>CFBundleDisplayName</key><string>{{app_name}}</string>
        <key>CFBundleIdentifier</key><string>{{bundle_id}}</string>
        <key>CFBundleVersion</key><string>{{version}}</string>
        <key>CFBundleShortVersionString</key><string>{{version}}</string>
        <key>CFBundleExecutable</key><string>{{app_name}}</string>
        <key>CFBundleIconFile</key><string>AppIcon</string>
        <key>CFBundlePackageType</key><string>APPL</string>
        <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
        <key>LSMinimumSystemVersion</key><string>12.0</string>
        <!-- NOT an LSUIElement/agent app. With LSUIElement the main window
             belongs to a background agent: no Dock tile, skipped by Cmd+Tab
             and Mission Control, and unmanageable by window managers — it
             just floats. The app switches itself to the accessory policy at
             runtime instead (src/ui/activation.rs), so it is only menu-bar
             only while its window is closed. -->
        <key>LSUIElement</key><false/>
        <key>NSHighResolutionCapable</key><true/>
        <key>NSMicrophoneUsageDescription</key><string>{{app_name}} needs the microphone to transcribe speech.</string>
        <key>NSSpeechRecognitionUsageDescription</key><string>{{app_name}} processes speech locally for dictation.</string>
        <!-- Required for Core Audio process taps (macOS 14.4+), which is how
             meeting audio from other participants is captured without a
             virtual audio driver. Without this key the tap fails to create. -->
        <key>NSAudioCaptureUsageDescription</key><string>{{app_name}} records the audio of your meetings so it can transcribe what the other participants say.</string>
    </dict>
    </plist>
    PLIST
    codesign --force --deep --sign - "{{app_bundle}}"
    echo "bundled: {{app_bundle}}"

# Build plain release binary, bundle into a .app, and wrap it in the installer .dmg.
bundle: build _bundle _dmg

# Same with the sherpa-onnx backend (NeMo Parakeet).
bundle-sherpa: build-sherpa _bundle _dmg

# --- disk image ------------------------------------------------------------

# Wrap the existing .app into a drag-and-drop installer disk image: the app on
# the left, an alias to /Applications on the right, drop one onto the other.
# Part of `bundle`, so every build that produces a .app produces the installer
# next to it; runnable on its own as `just _dmg` when only the image changed.
#
# Built in two passes on purpose. A Finder window layout (icon positions, view
# options) can only be recorded into a *writable* volume's .DS_Store, so a UDRW
# image is created, mounted, arranged, and only then converted to the
# compressed read-only image that ships. Everything Finder-related is optional:
# if macOS denies the automation prompt the layout is skipped and the disk
# image is still produced, just with default icon positions.
_dmg:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -d "{{app_bundle}}" ]; then
        echo "missing {{app_bundle}} — run 'just bundle' (or 'just bundle-sherpa') first" >&2
        exit 1
    fi

    mountpoint="/Volumes/{{app_name}}"
    hdiutil detach "$mountpoint" >/dev/null 2>&1 || true
    rm -rf "{{dmg_staging}}" "{{dmg_rw}}" "{{dmg}}"

    # What the window shows: the app, and the drop target next to it.
    mkdir -p "{{dmg_staging}}"
    cp -R "{{app_bundle}}" "{{dmg_staging}}/"
    ln -s /Applications "{{dmg_staging}}/Applications"
    # Same artwork as the app icon, so the mounted volume is recognisable.
    cp "{{app_bundle}}/Contents/Resources/AppIcon.icns" "{{dmg_staging}}/.VolumeIcon.icns"

    # Auto-sizing leaves no room for the .DS_Store written while arranging.
    size_mb=$(( $(du -sm "{{dmg_staging}}" | cut -f1) + 50 ))
    hdiutil create -volname "{{app_name}}" -srcfolder "{{dmg_staging}}" \
        -fs HFS+ -format UDRW -size "${size_mb}m" -ov "{{dmg_rw}}" >/dev/null

    # Mounted at a known path so nothing has to be parsed out of hdiutil's
    # output, and Finder-visible (no -nobrowse) so the layout can be set.
    hdiutil attach -readwrite -noverify -noautoopen -mountpoint "$mountpoint" \
        "{{dmg_rw}}" >/dev/null
    trap 'hdiutil detach "$mountpoint" >/dev/null 2>&1 || true' EXIT

    osascript <<'APPLESCRIPT' >/dev/null 2>&1 || echo "note: Finder layout skipped (automation not permitted)"
    tell application "Finder"
        tell disk "{{app_name}}"
            open
            set current view of container window to icon view
            set toolbar visible of container window to false
            set statusbar visible of container window to false
            set the bounds of container window to {200, 140, 800, 540}
            set opts to the icon view options of container window
            set arrangement of opts to not arranged
            set icon size of opts to 112
            set position of item "{{app_name}}.app" of container window to {150, 190}
            set position of item "Applications" of container window to {450, 190}
            update without registering applications
            close
        end tell
    end tell
    APPLESCRIPT

    # Tell the Finder to use .VolumeIcon.icns. SetFile ships with the Xcode
    # command line tools; without it the volume just keeps the generic icon.
    if command -v SetFile >/dev/null 2>&1; then
        SetFile -a C "$mountpoint" || true
    fi

    sync
    # The Finder can hold the volume for a moment after closing the window,
    # and a busy detach here would throw away the whole build.
    detached=0
    for _ in 1 2 3 4 5; do
        if hdiutil detach "$mountpoint" >/dev/null 2>&1; then detached=1; break; fi
        sleep 1
    done
    if [ "$detached" -eq 0 ]; then
        hdiutil detach "$mountpoint" -force >/dev/null
    fi
    trap - EXIT
    hdiutil convert "{{dmg_rw}}" -format UDZO -imagekey zlib-level=9 -o "{{dmg}}" >/dev/null
    rm -f "{{dmg_rw}}"
    rm -rf "{{dmg_staging}}"
    # One line, because this now runs on every bundle and install. The bundle
    # inside is ad-hoc signed and not notarized, so a *downloaded* copy is
    # blocked on first launch — locally built ones are not.
    echo "disk image: {{dmg}} — ad-hoc signed, not notarized: on another Mac, right-click → Öffnen, or 'xattr -dr com.apple.quarantine {{installed_app}}'"

# Write the app icon out as PNGs (16 … 1024 px, plus the menu-bar mark) so
# the artwork can be looked at without installing the bundle.
icons out="target/icons": build
    "{{bin}}" --write-icon-pngs "{{out}}"
    @open "{{out}}" 2>/dev/null || true

# --- install ---------------------------------------------------------------

# Copy the already-built .app into /Applications. Fails if the bundle is missing.
_install:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -d "{{app_bundle}}" ]; then
        echo "missing {{app_bundle}} — run 'just bundle' (or 'just bundle-sherpa') first" >&2
        exit 1
    fi
    rm -rf "{{installed_app}}"
    cp -R "{{app_bundle}}" "{{install_root}}/"
    # LaunchServices caches Info.plist per bundle id, and a stale entry from a
    # build that set LSUIElement keeps launching the app as a background agent
    # (no Dock tile, no Cmd+Tab) however the new plist reads. Re-register so
    # the installed bundle is what the OS actually believes.
    lsregister=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
    [ -x "$lsregister" ] && "$lsregister" -f "{{installed_app}}" || true
    echo "installed: {{installed_app}}"

# Full plain pipeline: build → bundle → .dmg → install to /Applications.
install: bundle _install

# Full sherpa pipeline: build with sherpa feature → bundle → .dmg → install.
install-sherpa: bundle-sherpa _install

# Remove the installed .app
uninstall:
    rm -rf {{installed_app}}
    @echo "removed: {{installed_app}}"

# --- combined --------------------------------------------------------------

# Full pipeline: build release binary, bundle into .app, install to /Applications
release: install
    @echo "release ready: {{installed_app}}"

# Full pipeline with the sherpa-onnx backend (NeMo Parakeet). First build ~10 min.
release-sherpa: install-sherpa
    @echo "release ready (sherpa): {{installed_app}}"

# --- run / dev -------------------------------------------------------------

# Build, sign, run with default logging
run: build
    RUST_LOG="whisprking=info,info" ./{{bin}}

# Run with the sherpa-onnx backend enabled
run-sherpa: build-sherpa
    RUST_LOG="whisprking=info,info" ./{{bin}}

# Build, sign, run with verbose tracing + backtraces
trace: build
    RUST_LOG="whisprking=trace" RUST_BACKTRACE=full ./{{bin}}

# --- maintenance -----------------------------------------------------------

# Clear every macOS Accessibility entry. Next launch triggers fresh prompt.
reset-trust:
    tccutil reset Accessibility
    @echo "All Accessibility entries reset. Run 'just run' and accept the prompt."

# Full reset: clear trust + clean build + sign + run
fresh: reset-trust
    cargo clean
    just run

test:
    cargo test --lib

check:
    cargo check
    cargo clippy --all-targets -- -D warnings

clean:
    cargo clean
    rm -rf {{bundle_dir}}
